CREATE MATERIALIZED VIEW "DB2ADMIN"."MV_LH_CONTRACT_MASTER"						
ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING						
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645						
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)						
TABLESPACE "USERSPACE1" 						
BUILD IMMEDIATE						
USING INDEX 						
REFRESH FORCE ON DEMAND						
USING DEFAULT LOCAL ROLLBACK SEGMENT						
DISABLE QUERY REWRITE						
AS SELECT *						
FROM         DB2ADMIN.LH_CONTRACT_MASTER						
WHERE     (HC_CN_RUNNO_SHOW IS NOT NULL) AND (HC_FLAG = 'A') AND (HC_CN_STATUS NOT IN ('0S', '0C'));


CREATE MATERIALIZED VIEW "DB2ADMIN"."MV_LH_OUTSTANDING"						
ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING						
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645						
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)						
TABLESPACE "USERSPACE1" 						
BUILD IMMEDIATE						
USING INDEX 						
REFRESH FORCE ON DEMAND						
USING DEFAULT LOCAL ROLLBACK SEGMENT						
DISABLE QUERY REWRITE						
AS SELECT *						
FROM         DB2ADMIN.LH_OUTSTANDING						
WHERE     HO_CN_RUNNO_SHOW IN (SELECT HC_CN_RUNNO_SHOW FROM DB2ADMIN.MV_LH_CONTRACT_MASTER);						
						
CREATE MATERIALIZED VIEW "DB2ADMIN"."MV_LH_CONTRACT_INSTALMENT"						
ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING						
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645						
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)						
TABLESPACE "USERSPACE1" 						
BUILD IMMEDIATE						
USING INDEX 						
REFRESH FORCE ON DEMAND						
USING DEFAULT LOCAL ROLLBACK SEGMENT						
DISABLE QUERY REWRITE						
AS SELECT *						
FROM         DB2ADMIN.LH_CONTRACT_INSTALMENT						
WHERE     HCI_CN_RUNNO_SHOW IN (SELECT HC_CN_RUNNO_SHOW FROM DB2ADMIN.MV_LH_CONTRACT_MASTER);						
						
CREATE MATERIALIZED VIEW "DB2ADMIN"."MV_LH_CONTRACT_BALANCE"						
ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING						
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645						
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)						
TABLESPACE "USERSPACE1" 						
BUILD IMMEDIATE						
USING INDEX 						
REFRESH FORCE ON DEMAND						
USING DEFAULT LOCAL ROLLBACK SEGMENT						
DISABLE QUERY REWRITE						
AS SELECT *						
FROM         DB2ADMIN.LH_CONTRACT_BALANCE						
WHERE     HCB_CN_RUNNO_SHOW IN (SELECT HC_CN_RUNNO_SHOW FROM DB2ADMIN.MV_LH_CONTRACT_MASTER);						
						
CREATE MATERIALIZED VIEW "DB2ADMIN"."MV_LH_CONTRACT_CAR"						
ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING						
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645						
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)						
TABLESPACE "USERSPACE1" 						
BUILD IMMEDIATE						
USING INDEX 						
REFRESH FORCE ON DEMAND						
USING DEFAULT LOCAL ROLLBACK SEGMENT						
DISABLE QUERY REWRITE						
AS SELECT *						
FROM         DB2ADMIN.LH_CONTRACT_CAR						
WHERE     HCC_CN_RUNNO_SHOW IN (SELECT HC_CN_RUNNO_SHOW FROM DB2ADMIN.MV_LH_CONTRACT_MASTER);						
						
CREATE MATERIALIZED VIEW "DB2ADMIN"."MV_CT_CUSTOMER5"						
ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING						
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645						
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)						
TABLESPACE "USERSPACE1" 						
BUILD IMMEDIATE						
USING INDEX 						
REFRESH FORCE ON DEMAND						
USING DEFAULT LOCAL ROLLBACK SEGMENT						
DISABLE QUERY REWRITE						
AS SELECT *						
FROM         DB2ADMIN.CT_CUSTOMER5						
WHERE     C5_CUST_CODE IN (SELECT HC_CUST_CODE FROM DB2ADMIN.MV_LH_CONTRACT_MASTER);						

